#ifndef NENCRYPTIONKIT_GLOBAL_H
#define NENCRYPTIONKIT_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(NENCRYPTIONKIT_LIBRARY)
#  define NENCRYPTIONKITSHARED_EXPORT Q_DECL_EXPORT
#else
#  define NENCRYPTIONKITSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // NENCRYPTIONKIT_GLOBAL_H
